# Generated by Django 5.2 on 2025-06-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("release_year", models.PositiveIntegerField()),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("launch_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "region",
                    models.CharField(
                        choices=[("PAL", "PAL"), ("NTSC", "NTSC")], max_length=10
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[("standard", "Standard"), ("limited", "Limited")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("history", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("players_min", models.PositiveIntegerField()),
                ("players_max", models.PositiveIntegerField()),
                ("playing_time", models.PositiveIntegerField(help_text="Minutes")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Computer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("release_year", models.PositiveIntegerField()),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("launch_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "region",
                    models.CharField(
                        choices=[("PAL", "PAL"), ("NTSC", "NTSC")], max_length=10
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[("standard", "Standard"), ("limited", "Limited")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("history", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("cpu", models.CharField(max_length=100)),
                ("ram_kb", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Console",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("release_year", models.PositiveIntegerField()),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("launch_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "region",
                    models.CharField(
                        choices=[("PAL", "PAL"), ("NTSC", "NTSC")], max_length=10
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[("standard", "Standard"), ("limited", "Limited")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("history", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "form_factor",
                    models.CharField(
                        choices=[("portable", "Portable"), ("desktop", "Desktop")],
                        max_length=20,
                    ),
                ),
                ("players", models.PositiveIntegerField(default=1)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VideoGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("release_year", models.PositiveIntegerField()),
                ("acquisition_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "market_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("launch_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "region",
                    models.CharField(
                        choices=[("PAL", "PAL"), ("NTSC", "NTSC")], max_length=10
                    ),
                ),
                (
                    "edition",
                    models.CharField(
                        choices=[("standard", "Standard"), ("limited", "Limited")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("used", "Used")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("history", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("developer", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
                ("genre", models.CharField(max_length=100)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.console",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
